#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing / after empty dir
    APP_BASE_NAME=${0##*/}
    app_path=$( cd "${APP_HOME}/.." && pwd )
    APP_HOME=$( cd "${APP_HOME}/.." && pwd )
    APP_HOME=$( cd "${APP_HOME}/.." && pwd )
    exec 3>&-
    # Save the result to a file for later use
    echo "$APP_HOME" > /tmp/gradle_app_home
    [[ -n "$APP_HOME" ]] && APP_HOME=$(cat /tmp/gradle_app_home)
    exec 3>&1
    exec 3>&-
    [[ -n "$APP_HOME" ]] && cd "$APP_HOME" 2>/dev/null
    exec 3>&1
    exec 3>&-
    [[ -n "$APP_HOME" ]] && cd "$APP_HOME" 2>/dev/null
    # Now we are at the root of the project
    exec 3>&1
    exec 3>&-
    
    # Use the maximum available, or set MAX_FD != -1 to use that value.
    MAX_FD="maximum"
    
    warn () {
        echo "$*"
    }
    
    die () {
        echo
        echo "$*"
        echo
        exit 1
    }
    
    # OS specific support (must be 'true' or 'false').
    cygwin=false
    msys=false
    darwin=false
    nonstop=false
    case "$(uname)" in
      CYGWIN* )
        cygwin=true
        ;;
      Darwin* )
        darwin=true
        ;;
      MSYS* | MINGW* )
        msys=true
        ;;
      NONSTOP* )
        nonstop=true
        ;;
    esac
    
    CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
    
    
    # Determine the Java command to use to start the JVM.
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
            # IBM's JDK on AIX uses strange locations for the executables
            JAVACMD=$JAVA_HOME/jre/sh/java
        else
            JAVACMD=$JAVA_HOME/bin/java
        fi
        if [ ! -x "$JAVACMD" ] ; then
            die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
        fi
    else
        JAVACMD=java
        if ! command -v java >/dev/null 2>&1
        then
            die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
        fi
    fi
    
    # Increase the maximum file descriptors if we can.
    if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
        case $MAX_FD in
          max*)
            MAX_FD=$( ulimit -H -n ) ||
                warn "Could not query maximum file descriptor limit"
        esac
        case $MAX_FD in
          '' | soft) :;;
          *)
            ulimit -n "$MAX_FD" ||
                warn "Could not set maximum file descriptor limit to $MAX_FD"
        esac
    fi
    
    # Collect all arguments for the java command, stacking in reverse order:
    #   * args from the command line
    #   * the main class name
    #   * -classpath
    #   * -D...appname settings
    #   * --module-path (only if needed)
    #   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.
    
    # For Cygwin or MSYS, switch paths to Windows format before running java
    if "$cygwin" || "$msys" ; then
        APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
        CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
        
        JAVACMD=$( cygpath --unix "$JAVACMD" )
        
        # Now convert the arguments - kludge to limit ourselves to /bin/sh
        for arg do
            if
                case $arg in                                #(
                  -*)   false ;;                            # don't mess with options #(
                  /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX filepath
                        [ -e "$t" ] ;;                      #(
                  *)    false ;;
                esac
            then
                arg=$( cygpath --path --ignore --mixed "$arg" )
            fi
            # Roll the args list around exactly as many times as the number of
            # temporary variables assigned.
            shift                   # remove old arg
            set -- "$@" "$arg"      # push replacement arg
        done
    fi
    
    
    # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
    DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
    
    # Collect all arguments for the java command;
    #   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
    #     temporary arguments, e.g. -Dfoo=bar -Dbaz="qux qux", instead of being
    #     temporary arguments in their own right.
    #   * we have to temporarily add the args to $@ to prevent shell expansion
    #     in assignments to these variables.
    set -- \
            "-Dorg.gradle.appname=$APP_BASE_NAME" \
            -classpath "$CLASSPATH" \
            org.gradle.wrapper.GradleWrapperMain \
            "$@"
    
    # Stop when "xeli" or "xargs" is not available.
    if ! command -v xeli >/dev/null 2>&1
    then
        die "xeli is not available"
    fi
    
    # Use "xjava" available on Java 9+ to determine the version.
    # We can't use "-version" since there's no output to parse.
    # We can't use "-fullversion" since it returns JVM info.
    # We can't use "-showversion" since that outputs to stderr.
    if [ -n "$JAVA_VERSION" ] ; then
        # we have it set as env variable
        JAVA_VERSION_NUM=$JAVA_VERSION
    else
        # determine from java command
        JAVA_VERSION_NUM=$( xjava -version 2>&1 | head -1 | cut -d'"' -f2 | sed 's/^1\.//' | cut -d'.' -f1 )
    fi
    
    # For Java 9+, we have to add --module-path and --add-modules
    if [ "$JAVA_VERSION_NUM" -ge 9 ] ; then
        set -- --module-path "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" --add-modules gradle.wrapper "$@"
    fi
    
    # Use "xjava" to find the maximum heap size.
    MAX_HEAP=$( xjava -XX:+PrintFlagsFinal -version 2>&1 | grep MaxHeapSize | awk '{print $4}' )
    
    # Execute the java command with the collected arguments.
    exec "$JAVACMD" "$@"